logging:
  level:
    ROOT: INFO

monitor:
  restartCmdFormat: bash -c "sleep 10"

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"

  security:
    enabled: false

info:
  app:
    name: "Monitor"
    description: "Used monitoring processes"
