spring:
  boot:
    admin:
      client:
        url: ${spring.admin.clienturl}

    application:
      name: Middle Tier Monitor

logging.file: /var/log/jbr/MiddleTier-Monitor-PDN.log
logging:
  file:
    max-history: 3
    max-size: 100MB

server.port: 12021

monitor:
  service.name: "Middle Tier Monitor"
  schedule: "15 0/8 * * * ?"
  schedule.restart: "15 7 0 * * ?"
  web-log-url: http://192.168.1.64:12001/jbr/int/log/data
